In [1]:
import numpy as np
import matplotlib.pyplot as plt
from skimage.io import imread, imshow
from skimage.draw import disk
from skimage.morphology import (erosion, dilation, closing, opening,
                                area_closing, area_opening)
from skimage.color import rgb2gray

a = np.array([
    [0,0,1,1,0],
    [0,0,1,1,0],
    [0,0,1,1,0],
    [1,1,1,1,1]
])

s = np.array([
        [1],
        [1],
        [1]])

image = np.array(erosion(a,s))
print(image)

[[0 0 1 1 0]
 [0 0 1 1 0]
 [0 0 1 1 0]
 [0 0 1 1 0]]
